[tools]
luau-lsp = "johnnymorganz/luau-lsp@1.18.1"
rojo = "rojo-rbx/rojo@7.2.1"
selene = "Kampfkarren/selene@0.25.0"
stylua = "johnnymorganz/stylua@0.17.1"
wally = "grilme99/wally@0.4.0"
wally-package-types = "johnnymorganz/wally-package-types@1.2.1"